### ISSUE TITLE
Regarding JedAIToolkit sample csv file

### ISSUE THREAD

**Issue by sumanatcs** [scify/JedAIToolkit#1]
I am looking at the source code of JedAIToolkit in github.

I am not able to find the sample csv file for testing.

Can I get the cd_gold.csv and cd.csv file which has been used for testing purpose of TestGtCSVReader.java & TestEntityCSVReader.java.

**Comment by gpapadis** [comment]
Hi,

we are glad that you are interested in our work. You can download the CDDB dataset from here: https://hpi.de/naumann/projects/data-quality-and-cleansing/dude-duplicate-detection.html#c114715

Best regards,
George

**Comment by sumanatcs** [comment]
Hi George,

Thanks you so much for your quick response!

It helps a lot!

Regards,
Sumana
