### ISSUE TITLE
Deploy To Maven Central

### ISSUE THREAD

**Issue by allan-shoup** [scify/JedAIToolkit#22]
To make it easier to consume, can the project be deployed to Maven Central?

**Comment by xstrtok** [comment]
Hi Allan,
we have begun working on uploading the artifacts to maven central.

We'll notify you and close the issue once the artifacts are accepted and uploaded.

**Comment by xstrtok** [comment]
As of today:
- builds exists in maven central
- added some changes in the pom files to reflect those changes

Closing this issue as it's resolved.

Feel free to re-open the issue if for some reason you can't see the deployed artifacts.

Remember you need to update the repository *AND* the submodule to be able to build.

**Comment by allan-shoup** [comment]
I see the transitive dependencies have been deployed to Maven Central (thank you for that). Can jedai-core also be deployed? It would be beneficial if Issue #23 were resolved before this happens.
