### ISSUE TITLE
Remove maven-assembly-plugin Configuration From jeda-core

### ISSUE THREAD

**Issue by allan-shoup** [scify/JedAIToolkit#23]
If another project is going to depend on jedai-core, having the transitive dependencies assembled inside jedai-core has the potential to conflict if different versions of those same transitive dependencies are needed for the other project. Since jedai-ui is already assembling transitive dependencies, removing transitive dependencies from jedai-core should not have any effect on the UI.

**Comment by allan-shoup** [comment]
Pull request to solve this issue: https://github.com/scify/JedAIToolkit/pull/25

**Comment by xstrtok** [comment]
As the pull request is merged, I'm closing this issue.
