### ISSUE TITLE
Reduce memory footprint of SimilarityPairs

### ISSUE THREAD

**Issue by allan-shoup** [scify/JedAIToolkit#34]
We're using jedai-core (not jedai-ui) in our application and we ran into some Out of Memory errors and started profiling our application. The largest chunk of memory was from SimilarityPairs. We experimented with reducing the size of the `similarities` from double to float and that reduced the memory footprint by about 25% (630 MB -> 470 MB).

I'm assuming we don't need the extra precision afforded by double, is that correct?

**Comment by allan-shoup** [comment]
Added a pull request for this issue: https://github.com/scify/JedAIToolkit/pull/35

**Comment by gpapadis** [comment]
Hi Allan,

thanks a lot for the recommendation! It is indeed quite helpful for reducing the memory footprint. Feel free to propagate the changes to all affected classes. I will also have a look at the code during the weekend.

Kind regards,
George

**Comment by allan-shoup** [comment]
Added an additional pull request for the remaining changes: https://github.com/scify/JedAIToolkit/pull/36
