### ISSUE TITLE
Unable to load csv

### ISSUE THREAD

**Issue by msalkic** [scify/JedAIToolkit#37]
I am using the latest JedAI-gui: jedai-ui.7z. I tried loading DBLP-ACM .csv data:
1. ACM.csv
2. DBLP2.csv
3. DBLP-ACM_perfectMapping.csv

and I get the following error (please see attached):
![Screenshot 2020-05-25 at 15 20 31](https://user-images.githubusercontent.com/19351189/82838770-34223d00-9e9b-11ea-8bfd-5ab9ca3e6171.png)

**Comment by gpapadis** [comment]
Hi! 
We are working on fixing the bug. In the meantime, you could use JedAI's web app. Here is a video explaining how to run it: https://www.youtube.com/watch?v=OJY1DUrUAe8&t=24s . Make sure, though, to remove the quotes from the groundtruth file. 
An alternative is to use the parsed datasets that are available here: https://github.com/scify/JedAIToolkit/tree/master/data . JedAI-gui processes without problems.
Regards,
George

**Comment by msalkic** [comment]
Thank you
