### ISSUE TITLE
data pairs shown as false negatives and as true positives

### ISSUE THREAD

**Issue by saphyll** [scify/JedAIToolkit#39]
I found some cases where data pairs showed up in the end results as false negative and true positive simultaneously.
Its cause is in the class `UnilateralDuplicatePropagation` and the following functions:
```
public boolean isSuperfluous(int entityId1, int entityId2) {
        final IdDuplicates duplicatePair1 = new IdDuplicates(entityId1, entityId2);
        final IdDuplicates duplicatePair2 = new IdDuplicates(entityId2, entityId1);
        if (duplicates.contains(duplicatePair1)
                || duplicates.contains(duplicatePair2)) {
            if (entityId1 < entityId2) {
                detectedDuplicates.add(duplicatePair1);
            } else {
                detectedDuplicates.add(duplicatePair2);
            }
        }

        return false;
    }
```
```
public Set<IdDuplicates> getFalseNegatives() {
        final Set<IdDuplicates> falseNegatives = new HashSet<>(duplicates);
        falseNegatives.removeAll(detectedDuplicates);
        return falseNegatives;
    }
```
Only one of two possible combinations of IDs is written to detectedDuplicates, but superfluous combinations still exist in duplicates. When removing detectedDuplicates from duplicates to create falseNegatives, those superfluous combinations remain and are exported as false negatives, while the combinations in detectedDuplicates are exported as true positives.

**Comment by gpapadis** [comment]
Thanks for pointing this bug out to us! It should be fixed by the latest commit.
