### ISSUE TITLE
Could not read successfully the input file!

### ISSUE THREAD

**Issue by baditaflorin** [scify/JedAIToolkit#41]
How do I create a ground Truth file?

**Comment by GiorgosMandi** [comment]
Hello,

A ground-truth file is a file (i.e. .csv) containing pairs of ids of entities that match. 
If you want to use JedAI without a ground-truth file, you can use the latest [docker image ](https://hub.docker.com/repository/docker/gmandi/jedai-webapp) of the web-app which enables the execution of workflows without a ground-truth file.

This ground-truth-free execution is under development, so if any issue arise let us know
