### ISSUE TITLE
CSV Headers with upper case doesn't works for PPJoin 

### ISSUE THREAD

**Issue by AbhayPore** [scify/JedAIToolkit#42]
In Similarity join page on UI, on providing the Select attribute of Dataset 1: & Select attribute of Dataset 2: value with uppercase value Eg: "INSTANCE ID", the algorithm fails to match results. On further investigating I found that the class `AbstractSimilarityJoin` method `getAttributeValue(String attributeName, EntityProfile profile)` on line 67 the `attributeName` should be changed to `attributeName.toLowerCase()` for considering attributeNames properly or else it simply ignores the if condition.

**Comment by gpapadis** [comment]
Thank you very much indeed for pointing out this bug! We have fixed it as suggested.
Kind regards,
George
