### ISSUE TITLE
Documentation or examples for the open source library

### ISSUE THREAD

**Issue by florisheijmans** [scify/JedAIToolkit#43]
I cannot seem to find any documentation or examples of a standard workflow implemented in python or java in your repository. Do either of these exist? If so, where could I find them? If not, it would be very useful to have these, since a new user of your tool like me now has to go through all of the java classes to learn how to use the tool, which will take a lot of time.

**Comment by gpapadis** [comment]
Hi!

We are working on providing more documentation for JedAI.

At the moment, you can find some presentations and publications on JedAI here: https://github.com/scify/JedAIToolkit/tree/master/documentation

There is also a video demonstrating JedAI's web application here: https://www.youtube.com/watch?v=OJY1DUrUAe8&t=3s

Examples for using JedAI's classes can be found here: https://github.com/scify/JedAIToolkit/tree/master/src/test/java/org/scify/jedai

For instance, all experiments described in the latest publication (http://cgi.di.uoa.gr/~koubarak/publications/2020/JedAI_3D_ER.pdf) can be run through the following classes:
https://github.com/scify/JedAIToolkit/tree/master/src/test/java/org/scify/jedai/version3

Kind regards,
George

**Comment by florisheijmans** [comment]
Hi George,

Thank you for the swift response!

I didn't think to look in the test folder, but those examples really help to speed up the process of implementing your tool.

Additionally, I have been reading some of your works in the process of forming a theoretical background for my thesis and I have to say that I have learned a lot from them. I wanted to thank you for that.

With kind regards,

Floris

**Comment by gpapadis** [comment]
Thank you for the kind words and your interest in our work!
Best regards,
George
