### ISSUE TITLE
Cannot read ground truth

### ISSUE THREAD

**Issue by Axande** [scify/JedAIToolkit#46]
There is a bug in the code that prevents the ground-truth in CSV format from being read. I tried the samples provided and the web-based docker image failed to load it. I downloaded the code and run it step by step and I think there is a problem with the GtCSVReader. The reading part takes strings like "thisisastring" where only thisisastring should be read. I tried to add nextLine[0] = nextLine[0].substring(1, nextLine[0].length()-1); on line 200 in that file, but no success so far. I need to make it work to test some CSV entity matchings, so maybe somebody has the fix for this issue?

**Comment by mthanos** [comment]
Hi, you can check #44 and resolve the issue by modifying your input files for now.
