### ISSUE TITLE
Dirty datasets in CSV format

### ISSUE THREAD

**Issue by florisheijmans** [scify/JedAIToolkit#47]
Hi I was wondering if you have the dirty datasets available in CSV format? Otherwise I can just create a quick script that reads the JSO files and convert them myself, but I figured there is no harm in asking first! Thanks in advance.

**Comment by gpapadis** [comment]
Hi! 

@florisheijmans: somehow I missed your ticket. I apologize for not replying.

@vromaniello: your data looks fine. Are the rest of the CSV reader parameters properly configured? You can send me a sample of your data (~50 rows) to try them myself.

**Comment by vromaniello** [comment]
Hi @gpapadis, my tests succedeed with JedAI's web app through Docker and following "Abt-Buy" .csv examples.
These are my files:

Entity profile

![image](https://user-images.githubusercontent.com/87575909/174655944-9a22eb85-ebac-4489-844f-88406de3ad1c.png)

Gold-truth file

![image](https://user-images.githubusercontent.com/87575909/174655987-c0d9e5d2-a32d-4c70-9fa3-fae645678b29.png)

The csv reader and the explore button work fine. 
Thank you
