### ISSUE TITLE
Change comparison counts type to int

### ISSUE THREAD

**Issue by eni-veres** [scify/JedAIToolkit#48]
We're using jedai-core in our application and we ran into some issues where the number of executed comparisons in ComparisonIterator was going over the number of total comparisons. We identified that this was happening because executedComparisons and totalComparisons are floats and changing them to ints fixed the problem. In Java, comparing two floats for exact equality is [generally discouraged](https://stackoverflow.com/questions/1088216/whats-wrong-with-using-to-compare-floats-in-java).

**Comment by eni-veres** [comment]
Added a pull request for this issue https://github.com/scify/JedAIToolkit/pull/49

**Comment by gpapadis** [comment]
That was really helpful! Thanks!
