### ISSUE TITLE
JedAI for Data matching

### ISSUE THREAD

**Issue by naserahmadi** [scify/JedAIToolkit#56]
Hello, 
I am trying to run Web based application for a data matching task. I have two tables in the csv format: the first table contains 1.2k rows and the second table contains 7k queries.  I want to use JedAI to match each query with a row from the first table. When I run a "block-based workflow" the process stuck in the table loading. 
I am a bit lost about how to configure the model. So far I tried the settings in the video tutorial and some other settings but the application never generates any outputs.  I share the  [Tables](https://drive.google.com/drive/folders/1TLVpzvJ5aD6yo6LzZzhrNKHQ7OIMN5h2?usp=sharing) with the message, please let me know if there is anything wrong with the way i generated them.

**Comment by gpapadis** [comment]
Hi!
You should add a column in the file Corona_claims.csv that indicates the unique id of every record (e.g., the number of the row). The same should be done with Corona_table.csv. Then, the file Corona_GT.csv should contain rows of the form 'id from Corona_claims.csv , id from Corona_claims.csv'. 
I am not sure, though, that this is a good application for ER. Essentially, the only distinctive information per entity is the country. All other tokens in the entity descriptions are the same, except for some numbers.
