### ISSUE TITLE
Make block building, block processing, entity clustering classes serializable and add setters for configurable fields

### ISSUE THREAD

**Issue by eni-veres** [scify/JedAIToolkit#57]
Having the blocking and clustering related classes serializable enables the usage of jedai-core in applications run in Hadoop and Spark clusters.
Having setters for the configurable fields add more flexibility in creating the blocking and clustering objects.

**Comment by eni-veres** [comment]
Added a pull request for this issue https://github.com/scify/JedAIToolkit/pull/58

**Comment by gpapadis** [comment]
Thank you for helping us to improve JedAI!
