### ISSUE TITLE
Apply JedAI blocking programmatically - missing documentation

### ISSUE THREAD

**Issue by NguyenQS** [scify/JedAIToolkit#62]
Hi!

I have successfully made the Web application work and I also made my first successful steps by using JedAI with Python.

But now I want to do it programatically with Python and without the Web application, so I want to apply the full workflow but only with the terminal and the VS Code.

But I couldn't find any detailed documentation how I can do blocking, cleaning ... programatically.

**Comment by Nikoletos-K** [comment]
Hello!

If I understand correctly, you need [pyJedAI](https://github.com/AI-team-UoA/pyJedAI) instead. pyJedAI is JedAI in python ecosystem. There you can create workflows using native python. Also, we suggest you to visit our [tutorials](https://github.com/AI-team-UoA/pyJedAI/tree/main/tutorials) and figure out which is the one that fits your task, as documentation is still under development.

**Comment by NguyenQS** [comment]
Hello!

It helps. Thanks you very much.
