### ISSUE TITLE
Converting the DBPedia dataset into non-Java format

### ISSUE THREAD

**Issue by moemode** [scify/JedAIToolkit#65]
Hello,
im working on converting the DBPedia dataset into a format accessible without Java.
I have already converted cleanDBPedia1/2. 
However i do not understand the ground truth format. 
The profiles have attributes and a URI. 
The pairs in the ground truth consist of numbers.
However, when i interpret these numbers as offsets into either file i end up with non-matching pairs.
I wrote the entities into the files in the order they were in the deserialized Java list.
How to find matching pairs / understand the grund truth?
Kind regards

**Comment by gpapadis** [comment]
Hi,

thank you for the interest in our work! I gues you are referring to this dataset: https://data.mendeley.com/public-files/datasets/4whpm32y47/files/1a89ef99-7195-449e-95ed-b49bb2a853c4/file_downloaded, right?
The groundtruth file contains pairs of ids, with the left one corresponding to the position of cleanDBPedia1 and the right one to cleanDBPedia2. The ids start from 0. 
Let me know if the problem persists.

 Kind regards,
 George
